import { PATH_HOTEL_SEARCH } from './common'

export const LIST_HOTEL_FOOTER = [
    {
        path: '/khach-san/an-giang',
        label: 'An Giang',
        isStrong: false,
    },
    {
        path: '/khach-san/ba-ria-vung-tau',
        label: 'Bà Rịa - Vũng Tàu',
        isStrong: true,
    },
    {
        path: '/khach-san/bac-giang',
        label: 'Bắc Giang',
        isStrong: false,
    },
    {
        path: '/khach-san/ben-tre',
        label: 'Bến Tre',
        isStrong: false,
    },
    {
        path: '/khach-san/binh-dinh',
        label: 'Bình Định',
        isStrong: false,
    },
    {
        path: '/khach-san/binh-duong',
        label: 'Bình Dương',
        isStrong: false,
    },
    {
        path: '/khach-san/binh-thuan',
        label: 'Bình Thuận',
        isStrong: true,
    },
    {
        path: '/khach-san/can-tho',
        label: 'Cần Thơ',
        isStrong: false,
    },
    {
        path: '/khach-san/da-nang',
        label: 'Đà Nẵng',
        isStrong: false,
    },
    {
        path: '/khach-san/dak-lak',
        label: 'Đắk Lắk',
        isStrong: false,
    },
    {
        path: '/khach-san/dien-bien',
        label: 'Điện Biên',
        isStrong: false,
    },
    {
        path: '/khach-san/dong-nai',
        label: 'Đồng Nai',
        isStrong: false,
    },
    {
        path: '/khach-san/ha-noi',
        label: 'Hà Nội',
        isStrong: true,
    },
    {
        path: '/khach-san/ha-tinh',
        label: 'Hà Tĩnh',
        isStrong: false,
    },
    {
        path: '/khach-san/hai-phong',
        label: 'Hải Phòng',
        isStrong: false,
    },
    {
        path: '/khach-san/hoa-binh',
        label: 'Hòa Bình',
        isStrong: false,
    },
    {
        path: '/khach-san/khanh-hoa',
        label: 'Khánh Hòa',
        isStrong: true,
    },
    {
        path: '/khach-san/lai-chau',
        label: 'Lai Châu',
        isStrong: false,
    },
    {
        path: '/khach-san/lam-dong',
        label: 'Lâm Đồng',
        isStrong: true,
    },
    {
        path: '/khach-san/lang-son',
        label: 'Lạng Sơn',
        isStrong: false,
    },
    {
        path: '/khach-san/lao-cai',
        label: 'Lào Cai',
        isStrong: false,
    },
    {
        path: '/khach-san/nghe-an',
        label: 'Nghệ An',
        isStrong: false,
    },
    {
        path: '/khach-san/ninh-binh',
        label: 'Ninh Bình',
        isStrong: false,
    },
    {
        path: '/khach-san/ninh-thuan',
        label: 'Ninh Thuận',
        isStrong: false,
    },
    {
        path: '/khach-san/phu-yen',
        label: 'Phú Yên',
        isStrong: false,
    },
    {
        path: '/khach-san/quang-binh',
        label: 'Quảng Bình',
        isStrong: false,
    },
    {
        path: '/khach-san/quang-nam',
        label: 'Quảng Nam',
        isStrong: true,
    },
    {
        path: '/khach-san/quang-ngai',
        label: 'Quảng Ngãi',
        isStrong: false,
    },
    {
        path: '/khach-san/quang-ninh',
        label: 'Quảng Ninh',
        isStrong: false,
    },
    {
        path: '/khach-san/quang-tri',
        label: 'Quảng Trị',
        isStrong: false,
    },
    {
        path: '/khach-san/thai-nguyen',
        label: 'Thái Nguyên',
        isStrong: false,
    },
    {
        path: '/khach-san/thanh-hoa',
        label: 'Thanh Hóa',
        isStrong: false,
    },
    {
        path: '/khach-san/thua-thien-hue',
        label: 'Thừa Thiên Huế',
        isStrong: true,
    },
    {
        path: '/khach-san/tien-giang',
        label: 'Tiền Giang',
        isStrong: false,
    },
    {
        path: '/khach-san/sai-gon-ho-chi-minh',
        label: 'TP Hồ Chí Minh',
        isStrong: true,
    },
    {
        path: '/khach-san/vinh-phuc',
        label: 'Vĩnh Phúc',
        isStrong: false,
    },
]

export const POPULAR_PLACES_DOMESTIC = [
    {
        label: 'Hà Nội',
        des1: '1000 khách sạn Hà Nội',
        des2: 'Cẩm nang du lịch Hà Nội',
        des3: 'Khuyến mại du lịch Hà Nội',
        image: 'https://statics.vntrip.vn/website/images/dest.373x181.01.png',
        keyword: 'ha-noi',
    },
    {
        label: 'Đà Nẵng',
        des1: '600 khách sạn Đà Nẵng',
        des2: 'Cẩm nang du lịch Đà Nẵng',
        des3: 'Khuyến mại du lịch Đà Nẵng',
        image: 'https://statics.vntrip.vn/website/images/dest.181x181.01.png',
        keyword: 'da-nang',
    },
    {
        label: 'Hội An',
        des1: '500 khách sạn Hội An',
        des2: 'Cẩm nang du lịch Hội An',
        des3: 'Khuyến mại du lịch Hội An',
        image: 'https://statics.vntrip.vn/images/dest/dest.181x181.02.png',
        keyword: 'quang-nam/hoi-an',
    },
    {
        label: 'Tp. Hồ Chí Minh',
        des1: '1500 khách sạn Tp. Hồ Chí Minh',
        des2: 'Cẩm nang du lịch Tp. Hồ Chí Minh',
        des3: 'Khuyến mại du lịch Tp. Hồ Chí Minh',
        image: 'https://statics.vntrip.vn/images/dest/dest.373x181.02.png',
        keyword: 'sai-gon-ho-chi-minh',
    },
    {
        label: 'Phú Quốc',
        des1: '350 khách sạn Phú Quốc',
        des2: 'Cẩm nang du lịch Phú Quốc',
        des3: 'Khuyến mại du lịch Phú Quốc',
        image: 'https://statics.vntrip.vn/images/dest/dest.373x181.03.png',
        keyword: 'kien-giang/phu-quoc',
    },
    {
        label: 'Nha Trang',
        des1: '500 khách sạn Nha Trang',
        des2: 'Cẩm nang du lịch Nha Trang',
        des3: 'Khuyến mại du lịch Nha Trang',
        image: 'https://statics.vntrip.vn/images/dest/dest.373x181.04.png',
        keyword: 'khanh-hoa/nha-trang',
    },
    {
        label: 'Đà Lạt',
        des1: '500 khách sạn Đà Lạt',
        des2: 'Cẩm nang du lịch Đà Lạt',
        des3: 'Khuyến mại du lịch Đà Lạt',
        image: 'https://statics.vntrip.vn/images/dest/dest.373x181.05.png',
        keyword: 'lam-dong/da-lat',
    },
]

export const POPULAR_PLACES_INTER = {
    bangkok: {
        label: 'Băng Cốc',
        des1: '2194 khách sạn Băng Cốc',
        des2: 'Cẩm nang du lịch Băng Cốc',
        des3: 'Khuyến mại du lịch Băng Cốc',
        image: 'https://statics.vntrip.vn/images/dest/bangkok-new.png',
        path: PATH_HOTEL_SEARCH + '?keyword=Bangkok&countryCode=TH&regionId=604',
    },
    seoul: {
        label: 'Seoul',
        des1: '1655 khách sạn Seoul',
        des2: 'Cẩm nang du lịch Seoul',
        des3: 'Khuyến mại du lịch Seoul',
        image: 'https://statics.vntrip.vn/images/dest/seoul-new.png',
        path: PATH_HOTEL_SEARCH + '?keyword=Seoul&countryCode=KR&regionId=3124',
    },
    kualalumpur: {
        label: 'Kuala Lumpur',
        des1: '1691 khách sạn Kuala Lumpur',
        des2: 'Cẩm nang du lịch Kuala Lumpur',
        des3: 'Khuyến mại du lịch Kuala Lumpur',
        image: 'https://statics.vntrip.vn/images/dest/kualalumpur-new.png',
        path: PATH_HOTEL_SEARCH + '?keyword=KualaLumpur&countryCode=MY&regionId=1951',
    },
    singapore: {
        label: 'Singapore',
        des1: '443 khách sạn Singapore',
        des2: 'Cẩm nang du lịch Singapore',
        des3: 'Khuyến mại du lịch Singapore',
        image: 'https://statics.vntrip.vn/images/dest/singapore-new.png',
        path: PATH_HOTEL_SEARCH + '?keyword=Singapore&countryCode=SG&regionId=161',
    },
}

export const DEFAULT_DESTINATION = [
    {
        type: 'region',
        regionnamelong: 'Ha Noi, VietNam',
        regionname_vi: 'Hà Nội',
        seo_url: 'ha-noi',
        regioncode: 'vn-p-66',
        regiontype: 'vntrip province',
        regionid: '66',
        provider: 'vntrip',
        regionnamelong_vi: 'Hà Nội, Việt Nam',
        countrycode: 'VN',
        countryname: 'Vietnam',
        regionname: 'Ha Noi',
    },
    {
        type: 'region',
        regionnamelong: 'Ho Chi Minh City, VietNam',
        regionname_vi: 'Thành phố Hồ Chí Minh',
        seo_url: 'sai-gon-ho-chi-minh',
        regioncode: 'vn-p-67',
        regiontype: 'vntrip province',
        regionid: '67',
        provider: 'vntrip',
        regionnamelong_vi: 'Thành phố Hồ Chí Minh, Việt Nam',
        countrycode: 'VN',
        countryname: 'Vietnam',
        regionname: 'Ho Chi Minh City',
    },
    {
        type: 'region',
        regionnamelong: 'Da Nang, VietNam',
        regionname_vi: 'Đà Nẵng',
        seo_url: 'da-nang',
        regioncode: 'vn-p-68',
        regiontype: 'vntrip province',
        regionid: '68',
        provider: 'vntrip',
        regionnamelong_vi: 'Đà Nẵng, Việt Nam',
        countrycode: 'VN',
        countryname: 'Vietnam',
        regionname: 'Da Nang',
    },
    {
        type: 'region',
        regionnamelong: 'Nha Trang City, Khanh Hoa, Vietnam',
        seo_url: 'khanh-hoa/nha-trang',
        regioncode: 'vn-c-86-960',
        regiontype: 'vntrip city',
        regionnamelong_vi: 'Thành phố Nha Trang, Khánh Hòa, Việt Nam',
        city_seo_url: 'nha-trang',
        countrycode: 'VN',
        countryname: 'Vietnam',
        regionname_vi: 'Thành phố Nha Trang',
        regionid: '960',
        provider: 'vntrip',
        regionname: 'Thanh pho Nha Trang',
        id: 'vntcities_960',
    },
    {
        type: 'region',
        regionnamelong: 'Thua Thien Hue, VietNam',
        regionname_vi: 'Thừa Thiên Huế',
        seo_url: 'thua-thien-hue',
        regioncode: 'vn-p-110',
        regiontype: 'vntrip province',
        regionid: '110',
        provider: 'vntrip',
        regionnamelong_vi: 'Thừa Thiên Huế, Việt Nam',
        countrycode: 'VN',
        countryname: 'Vietnam',
        regionname: 'Thua Thien Hue',
    },
    {
        type: 'region',
        regionnamelong: 'Sa Pa District, Lao Cai, Vietnam',
        seo_url: 'lao-cai/sapa',
        regioncode: 'vn-c-92-1032',
        regiontype: 'vntrip city',
        regionnamelong_vi: 'Huyện Sa Pa, Lào Cai, Việt Nam',
        city_seo_url: 'sapa',
        countrycode: 'VN',
        countryname: 'Vietnam',
        regionname_vi: 'Huyện Sa Pa',
        regionid: '1032',
        provider: 'vntrip',
        regionname: 'Huyen Sa Pa',
        id: 'vntcities_1032',
    },
    {
        type: 'region',
        regionnamelong: 'Hoi An City, Quang Nam, Vietnam',
        seo_url: 'quang-nam/hoi-an',
        regioncode: 'vn-c-100-1117',
        regiontype: 'vntrip city',
        regionnamelong_vi: 'Thành phố Hội An, Quảng Nam, Việt Nam',
        city_seo_url: 'hoi-an',
        countrycode: 'VN',
        countryname: 'Vietnam',
        regionname_vi: 'Thành phố Hội An',
        regionid: '1117',
        provider: 'vntrip',
        regionname: 'Thanh pho Hoi An',
        id: 'vntcities_1117',
    },
    {
        type: 'region',
        regionnamelong: 'Phan Thiet City, Binh Thuan, Vietnam',
        seo_url: 'binh-thuan/phan-thiet',
        regioncode: 'vn-c-128-1408',
        regiontype: 'vntrip city',
        regionnamelong_vi: 'Thành phố Phan Thiết, Bình Thuận, Việt Nam',
        city_seo_url: 'phan-thiet',
        countrycode: 'VN',
        countryname: 'Vietnam',
        regionname_vi: 'Thành phố Phan Thiết',
        regionid: '1408',
        provider: 'vntrip',
        regionname: 'Thanh pho Phan Thiet',
        id: 'vntcities_1408',
    },
    {
        type: 'region',
        regionnamelong: 'Ha Long City, Quang Ninh, Vietnam',
        seo_url: 'quang-ninh/ha-long',
        regioncode: 'vn-c-102-1148',
        regiontype: 'vntrip city',
        regionnamelong_vi: 'Thành phố Hạ Long, Quảng Ninh, Việt Nam',
        city_seo_url: 'ha-long',
        countrycode: 'VN',
        countryname: 'Vietnam',
        regionname_vi: 'Thành phố Hạ Long',
        regionid: '1148',
        provider: 'vntrip',
        regionname: 'Thanh pho Ha Long',
        id: 'vntcities_1148',
    },
    {
        type: 'region',
        regionnamelong: 'Ba Ria - Vung Tau, VietNam',
        regionname_vi: 'Bà Rịa - Vũng Tàu',
        seo_url: 'ba-ria-vung-tau',
        regioncode: 'vn-p-119',
        regiontype: 'vntrip province',
        regionid: '119',
        provider: 'vntrip',
        regionnamelong_vi: 'Bà Rịa - Vũng Tàu, Việt Nam',
        countrycode: 'VN',
        countryname: 'Vietnam',
        regionname: 'Ba Ria - Vung Tau',
    },
    {
        type: 'region',
        regionnamelong: 'Quy Nhon City, Binh Dinh, Vietnam',
        seo_url: 'binh-dinh/quy-nhon',
        regioncode: 'vn-c-125-1378',
        regiontype: 'vntrip city',
        regionnamelong_vi: 'Thành phố Quy Nhơn, Bình Định, Việt Nam',
        city_seo_url: 'quy-nhon',
        countrycode: 'VN',
        countryname: 'Vietnam',
        regionname_vi: 'Thành phố Quy Nhơn',
        regionid: '1378',
        provider: 'vntrip',
        regionname: 'Thanh pho Quy Nhon',
        id: 'vntcities_1378',
    },
    {
        type: 'region',
        regionnamelong: 'Phu Quoc District, Kien Giang, Vietnam',
        seo_url: 'kien-giang/phu-quoc',
        regioncode: 'vn-c-87-980',
        regiontype: 'vntrip city',
        regionnamelong_vi: 'Huyện Phú Quốc, Kiên Giang, Việt Nam',
        city_seo_url: 'phu-quoc',
        countrycode: 'VN',
        countryname: 'Vietnam',
        regionname_vi: 'Huyện Phú Quốc',
        regionid: '980',
        provider: 'vntrip',
        regionname: 'Huyen Phu Quoc',
        id: 'vntcities_980',
    },
]

export const HOTEL_FILTER_STAR = [
    {
        key: 'five_star',
        label: 'Khách sạn 5',
        value: 5,
        checked: false,
    },
    {
        key: 'four_star',
        label: 'Khách sạn 4',
        value: 4,
        checked: false,
    },
    {
        key: 'three_star',
        label: 'Khách sạn 3',
        value: 3,
        checked: false,
    },
    {
        key: 'two_star',
        label: 'Khách sạn 2',
        value: 2,
        checked: false,
    },
    {
        key: 'one_star',
        label: 'Khách sạn 1',
        value: 1,
        checked: false,
    },
]

export const HOTEL_FILTER_BY_PRICE = [
    {
        key: 'below_500k',
        label: 'Dưới 500000 ₫',
        checked: false,
        min: 0,
        max: 500000,
    },
    {
        key: 'from_500k_to_1m',
        label: '500.000 ₫ – 1.000.000 ₫',
        checked: false,
        min: 500000,
        max: 500000 * 2,
    },
    {
        key: 'from_1m_to_2m',
        label: '1.000.000 ₫ – 2.000.000 ₫',
        checked: false,
        min: 500000 * 2,
        max: 500000 * 4,
    },
    {
        key: 'from_2m_to_5m',
        label: '2.000.000 ₫ – 5.000.000 ₫',
        checked: false,
        min: 500000 * 4,
        max: 500000 * 10,
    },
    {
        key: 'more_than_5m',
        label: 'Trên 5000000 ₫',
        checked: false,
        min: 500000 * 10,
        max: Number.MAX_SAFE_INTEGER,
    },
]

export const HOTEL_SORT = [
    {
        sort_by: '',
        sort_mode: '',
        label: 'Được gợi ý',
    },
    {
        sort_by: 'price',
        sort_mode: 'asc',
        label: 'Giá thấp nhất',
    },
    {
        sort_by: 'price',
        sort_mode: 'desc',
        label: 'Giá cao nhất',
    },
    {
        sort_by: 'review',
        sort_mode: 'desc',
        label: 'Đánh giá cao',
    },
]
