apiVersion: apps/v1
kind: Deployment
metadata:
  name: fe-vntrip-vn
  namespace: __NAMESPACE__
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: fe-vntrip-vn
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: fe-vntrip-vn
    spec:
      containers:
      - image: __IMAGE_URL__
        imagePullPolicy: Always
        env:
          - name: NEXT_PUBLIC_CDN
            value: https://test.vntrip.vn/
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 40
          periodSeconds: 2
          successThreshold: 1
          tcpSocket:
            port: 3000
          timeoutSeconds: 2
        name: fe-vntrip-vn
        ports:
        - containerPort: 3000
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 40
          periodSeconds: 2
          successThreshold: 2
          tcpSocket:
            port: 3000
          timeoutSeconds: 2
        resources:
          limits:
            cpu: 800m
            memory: 800Mi
          requests:
            cpu: 300m
            memory: 200Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/localtime
          name: tz-hcm
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: registry
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /usr/share/zoneinfo/Asia/Ho_Chi_Minh
          type: ""
        name: tz-hcm